version: "3.8"

services:
  win7:
    image: dockurr/windows
    container_name: win7
    environment:
      VERSION: "7u"
      RAM_SIZE: "14G"
      CPU_CORES: "2"
    ports:
      - "3389:3389"
      - "8006:8006"
    restart: always
